name: chromos_is_2
description: "Приложение для учёта приборов Chromos IS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:

  http: ^1.1.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.0

  intl: ^0.20.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
